version: "3.5"
services:
    clickhouse:
      image: yandex/clickhouse-server
      env_file: .env
      ports:
        - "8123:8123"
        - "9002:9000"
        - "9009:9009"
      volumes:
        - ./data/clickhouse:/var/lib/clickhouse
        - ./config/config.xml:/etc/clickhouse-server/config.xml
        - ./config/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      ulimits:
        nproc: 65535
        nofile:
          soft: 262144
          hard: 262144
    app:
      build: src
      env_file: .env
      restart: always
      depends_on:
        - clickhouse
      volumes:
          - ./data/app:/app/data
